### ISSUE TITLE
Add Report for employee

### ISSUE THREAD

**Issue by additionsolutions** [ujjvala-addsol/addsol_hr#16]
On Employee screen he/she should able to get a report having following:
1. Public Information
2. Personal Information
3. HR Settings
4. Probation start and end date from Contract
5. Confirmation Date from Contract
6. Work Permit information from Contract

**Comment by ujjvala-odoo** [comment]
Added new report for employee:
https://github.com/ujjvala-addsol/addsol_hr/commit/4492af7d1a68a3730519d45d1e5e2ccd3e3fce38
