### ISSUE TITLE
Add a Module and remove Daily Job

### ISSUE THREAD

**Issue by additionsolutions** [ujjvala-addsol/addsol_hr#18]
Move the functionality of Daily Job to new Module.
This Module will do following:
1. This module will run as a pre-payroll processing
2. Output of this module is input to Payroll processing giving following values:
-----> a. Number of days person present (Salary to be paid for these days only)
3. This will also check half day , late mark
4. This module is configurable. If flag is set then only Payroll is dependent on Attendance otherwise it is not.

**Comment by ujjvala-odoo** [comment]
> Created a new module, which will be installed only when the flag is set from the HR Configuration in the settings menu.

**Comment by additionsolutions** [comment]
Please add functionality so that daily job is not required.

**Comment by ujjvala-odoo** [comment]
Done here: https://github.com/ujjvala-addsol/addsol_hr/commit/f71f824a3b40e3b8786381e332605d6b47407172
